### ISSUE TITLE
map_tree returns an error

### ISSUE THREAD

**Issue by nikhilram** [zachcp/phylogeo#22]
Hello there,

I am having little bit of a trouble with the map_tree function. It returns the following error - 

Scale for 'x' is already present. Adding another scale for 'x', which will replace the existing scale.
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (1-1,2-2) arrange gtable[layout]

I wondered if it was my tree file but the file went through phyloseq and surprisingly I got the same error message with the included epoxomicin_KS data. This must be an error on my part so any help with identifying or circumventing the issue would be greatly appreciated.

Thank you!

**Comment by zachcp** [comment]
Hi @nikhilram ,

Thanks for posting. It looks like the gridExtra package has been updated and is causing some issues. I will try to get a fix in but an easy workaround is to install an earlier version (<= 1.0). I'll try to get an update in the next few days.

zach cp

**Comment by nikhilram** [comment]
Hi @zachcp,

Thank you very much for pointing out the issue. I installed an older version of gridExtra and that did wonders. Your help is much appreciated!

Nikhil

**Comment by zachcp** [comment]
fixed in 0.96.1

I switched from gridExtra to cowplot for compound plotting. thanks for the bug repot - please file any other and/or feature requests.
