### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by bioinfonm** [zachcp/phylogeo#23]
Hello,

  I am trying to upgrade my version of phylogeo ‘0.99.6’. I using R version:
> R.version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          1.3                         
year           2015                        
month          03                          
day            09                          
svn rev        67962                       
language       R                           
version.string R version 3.1.3 (2015-03-09)
nickname       Smooth Sidewalk  

I get this error when I try and upgrade:
> devtools::install_github("zachcp/phylogeo")
Downloading github repo zachcp/phylogeo@master
Installing phylogeo
Skipping 1 packages not available: phyloseq
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/sz/c8lxp6kj6yq89fhnzt2nxqhc0000gn/T/RtmpD6Z86p/devtools5cb364d324f/zachcp-phylogeo-fd2de6b'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

* installing *source* package ‘phylogeo’ ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
Warning: replacing previous import by ‘leaflet::%>%’ when loading ‘phylogeo’
Note: the specification for S3 class “AsIs” in package ‘BiocGenerics’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Note: the specification for S3 class “connection” in package ‘BiocGenerics’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Note: the specification for S3 class “file” in package ‘BiocGenerics’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Note: the specification for S3 class “pipe” in package ‘BiocGenerics’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Note: the specification for S3 class “textConnection” in package ‘BiocGenerics’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘cowplot’ 0.4.0 is being loaded, but >= 0.5.0 is required
ERROR: lazy loading failed for package ‘phylogeo’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/phylogeo’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/phylogeo’
Error: Command failed (1)

**Comment by bioinfonm** [comment]
Found it! Wrong version of cowplot due to an old R install. Sorry

**Comment by zachcp** [comment]
@bioinfonm glad you're using the software; no problem at all.
